[app]
title = MyCalculator
package.name = mycalculator
package.domain = org.example
source.include_exts = py,kv,png,jpg,atlas
version = 0.1
requirements = python3,kivy
orientation = portrait
fullscreen = 1

# (str) Source code where your main.py is located
source.dir = .

# (str) The main .py file that runs the app
entrypoint = main.py

# (str) Icon of the application (optional)
# icon.filename = %(source.dir)s/icon.png

# (list) Supported orientations


# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (list) Permissions
android.permissions = INTERNET

# (bool) Presplash screen
# presplash.filename = %(source.dir)s/data/presplash.png

[buildozer]
log_level = 2
warn_on_root = 1
# (int) Android API to use
android.api = 30

# (str) Android NDK version to use
android.ndk = 23b

# (int) Minimum API your APK will support
android.minapi = 21

# (int) Target API your APK will support
android.target = android-30

# (str) Android SDK version to use
android.sdk = 24

# (bool) Enable AndroidX support
android.enable_androidx = True

# (list) Additional Java .jars to add to the libs
# android.add_jars = libs/some-library.jar

# (str) Path to Android NDK
# android.ndk_path =

# (str) Path to Android SDK
# android.sdk_path =

# (str) Path to Android AVD
# android.avd_path =

# (bool) Automatically accept SDK licenses
android.accept_sdk_license = True

# (str) Path to keystore file (for signing APK)
# android.keystore = mykeystore.keystore

# (str) Custom package name (default is autogenerated)
# android.package = org.example.mycalculator

# (str) Path to local.properties file (optional)
# android.local_properties =

# (bool) Enable Buildozer to use GitHub Actions or CI
buildozer.always_check_requirements = False

# (str) Directory to save build artifacts
bin.dir = bin

# iOS options — ignored for Android builds
ios.codesign.allowed = false
